version: 2

jobs:  
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/pcelvng/task
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -cover -race -v ./...
