# task_bus = "" # "" (stdout), "stdout" (default), "file", "nsq"

# "file" task bus options
# default = "./output-tasks.json"
#
# NOTE: the file will be truncated if it exists
#write_file = "./out_tasks.json" # absolute or relative

# "nsq" task bus options
#
# NOTE: localhost:4150 is used by default
#nsqd_hosts = ["localhost:4150"] # nsqd hosts - only accepts tcp port

# series of task building rules
[[rule]]
cron_rule = "* * * * *" # second minute hour mday month wday

# NOTE: for the nsq bus type the topic will
# be the same value as the task_type.
task_type = "task-type" # REQUIRED

# task_template can accept any string and supports the following
# datetime formating:
#
# {yyyy} (year - four digits: ie 2017)
# {yy}   (year - two digits: ie 17)
# {mm}   (month - two digits: ie 12)
# {dd}   (day - two digits: ie 13)
# {hh}   (hour - two digits: ie 00)
#
# Note: only supports 24 hour (military time) and always reported in
# UTC. Does not support higher granularity than hour.
task_template = "{yyyy}-{mm}-{dd}:{hh}" # REQUIRED

# offset in hours from the moment of creation
# if task runs at "2017-01-04T14:15" and the offset is -1
# then the task_template datetime would reflect "2017-01-04T13:00".
# Can accept a positive of negative value.
#
# Default is 0 (no offset)
#hour_offset = -1

# topic is not required and if not specified will default to
# the value of "task_type".
#topic = "task-topic"

# SAMPLE RULE SET
#
# [[rule]]
# cron_rule = "05 01 * * * *"
# task_type = "task-type-1"
# task_template = "{yyyy}-{mm}-{dd}"
# hour_offset = -2
# topic = "topic-override-1"

# [[rule]]
# cron_rule = "05 * * * * *"
# task_type = "task-type-2"
# task_template = "{yyyy}-{mm}-{dd}:{hh}"
# hour_offset = -2

# [[rule]]
# cron_rule = "10 05 * * * *"
# task_type = "task-type-3"
# task_template = "prefix:{yyyy}/{mm}/{dd}/{hh}"
# hour_offset = -2
