# in_bus = "" # "" (stdin), "stdin" (default), "file", "nsq"
# out_bus = "" # "" (stdout), "stdout" (default), "file", "nsq"

# "file" task bus options
# default = "./output-tasks.json"
#
# NOTE: the file will be truncated if it exists
#read_file = "./in_tasks.json"
#write_file = "./out_tasks.json"

# "nsq" task bus options
#
# NOTE: localhost:4150 is used by default
#nsqd_hosts = ["localhost:4150"] # nsqd hosts - only accepts tcp port
#lookupd_hosts = ["localhost:4161"] # only accept http port

# series of task building rules
[[rule]]
# NOTE: for the nsq bus type the topic will
# be the same value as the task_type.
task_type = "task-type" # REQUIRED
retries = 10
#wait_minutes = 0 # retry immediately (default)
#topic = "task-topic" # use task_type value by default otherwise use topic

# SAMPLE RULE SET
#
# [[rule]]
# task_type = "task-type-1"
# wait_minute = 10
# retries = 3
# topic = "topic-override-1"

# [[rule]]
# task_type = "task-type-2"
# wait_minute = 0
# retries = 10

# [[rule]]
# task_type = "task-type-3"
# wait_minute = 60
# retries = 5
# topic = "topic-override-3"

