bus = "" # "" (stdio), "stdio", "file", "nsq"
done_topic = "done"
done_channel = "retry"
#in_file = "./in.tsks.json" # file bus
#out_file = "./out.tsks.json" # file bus
#nsqd_hosts = ["localhost:4150"] # nsq bus; tcp port
#lookupd_hosts = ["localhost:4161"] # nsq bus; http port

[[rule]]
type = "task-type" # REQUIRED # acts as default topic
retry = 5 # REQUIRED
wait = "10s" # '1s' = 1 second, '1m' = 1 minute, '1h' = 1 hour, '1d' = 1 day
topic = "" # override task type as the topic

# SAMPLE RULE SET
#
# [[rule]]
# type = "task-type-1"
# wait = "10s" # wait 10 seconds then retry
# retry = 3 # retry up to 3 times
# topic = "topic-override-1"

# [[rule]]
# type = "task-type-2"
# wait = "" # immediately
# retry = 10

# [[rule]]
# type = "task-type-3"
# wait = "60m" # wait an hour
# retry = 5
# topic = "topic-override-3"

# [[rule]]
# type = "task-type-3"
# retry = 2

